training: #namespace

    hidden1: 128            #hidden num of first fully connect layer
    hidden2: 128            #hidden num of second fully connect layer 
    rate: 0.00001             #learning rate
    warmup: 300            #time without training but only filling the replay memory
    discount: 0.99          
    bsize: 256 # 32             #minibatch size
    rmsize: 5000 #6000000         #memory size
    window_length: 1         
    tau: 0.001              #for the soft update
    ou_theta: 0.15          #noise theta
    ou_sigma: 1.2           #noise sigma
    ou_mu: 0                #noise mu
    validate_episodes: 20   #how many episode to perform during validate experiment
    max_episode_length: 150
    validate_steps: 1000    #how many steps to perform a validate experiment
    output: 'weights'        #where to save the stuff
    plot_folder: 'plots'
    parent_dir: '/home/adriano/Desktop/thesis_ws/src/Shared_control_architecture'
    debug: 'debug'
    init_w: 0.003
    max_train_iter: 200000      
    sigma_decay: 0.9999
    sigma:  0.5          #SD of noise
    max_epochs: 500
    seed: -1
    delta_goal: 1.0
    n_frame: 3

rewards:
    R_safe: 0 #
    R_col: -100
    R_goal: 0 #-1 #-100
    R_end: 0 #100
    R_alpha: -1 #1 #5 #
    R_cmd: -1 #-1 #-100
  

controller:
    #mode: 'train'           #support option: train/test/direct
    rate: 10
    usr_rate: 5
    verbose: False
    env: 'static' #_complex' #'office_NO_walls'  #'inventory_intensive'        #which is the world you are using


    #for collision avoidance
    delta_coll: 1.5
    theta_coll: 0.785 #pi/4
    K_lin: 1.5
    K_ang: 0.5
    k_ac: 20.0

    #tiago
    taigoMBclear: 0.6   #the rad is approx 0.25 and the obstacles are 0.2

    poly_degree: 2
    n_actions: 3
    dt: 0.1









